### ISSUE TITLE
Background highlighting

### ISSUE THREAD

**Issue by babakks** [ExodiusStudios/vscode-comment-anchors#1]
Could you please add the ability to highlight label backgrounds? With highlighted backgrounds, label are easier to catch.

**Comment by macjuul** [comment]
Great suggestion! I've implemented label background color support in the latest version of comment anchors.

Thanks for using comment anchors!

**Comment by babakks** [comment]
Thank you for making that happen.

**Comment by GammaGames** [comment]
I'd love if this was extended a bit to match the styling options of a [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) extension.

It has a bunch of settings, but the one I'm looking for the most is `isWholeLine`, which makes the background color highlight the entire line instead of just behind the word.

Also, I know it's not related to this issue, but is there a reason we can't just use the highlight color for the icon color as well?

**Comment by macjuul** [comment]
@GammaGames Sounds good! I'll look into adding it as soon as possible.

As for the icons, unfortunately they cannot be modified further since they are premade icons.

I'm glad to hear you're enjoying comment anchors!

**Comment by GammaGames** [comment]
You're awesome, thank you!

I'm curious, can't you use a vector icon and set its font color, instead of using images? I've never looked into making extensions, so I don't know how feasible that is

**Comment by macjuul** [comment]
> 
> 
> You're awesome, thank you!
> 
> I'm curious, can't you use a vector icon and set its font color, instead of using images? I've never looked into making extensions, so I don't know how feasible that is

Theoretically it should be possible, however at this moment VS Code does not seem to supply such functionality to extension authors. I can only specify the path where it can find the icon, so for now making preset icons seems like the only way.
