### ISSUE TITLE
Suggestion: Match including ':'

### ISSUE THREAD

**Issue by gsabater** [ExodiusStudios/vscode-comment-anchors#12]
Hello,

I would like to propose an improvement to your awesome extension.
With the inclusion of the new `section` anchor, I find there is a problem that I'm having again the same issue as with the `todo` anchor.

Section is a fairly common word, as well as todo (in spanish), and teams use it in comments without the intention to add an anchor, for example:

``` 
* Hay que eliminar todo esto y rehacerlo de nuevo. (spanish)
* This section needs a refactoring
```

What I propose here would be adding the colon symbol to the anchor matchmaking by default, so only `todo:`, `section:`, `todo :` or `section :` are matched as anchors.

Thanks

**Comment by lonix1** [comment]
Not only that, but please match only if the keyword is at the beginning of the line.

Match this:

    // TODO foo bar

Don't match this:

    // foo bar TODO foo bar

**Comment by macjuul** [comment]
The most effective solution that covers both these cases is to build in a check for a comment start symbol followed by zero or more empty characters. This would mean I'll have to record a list of possible symbols that can be placed before an anchor (<!--, //, #, /*, /**, [line start], etc.), and possibly make it available as setting for users to edit.

This does mean anchors will stop functioning in strings, markdown files, etc. However this shouldn't be a problem for most people.

Opinions? @lonix1 @gsabater 

Also,

> I thought I could override the default keywords in the json config, but it did nothing. So this needs a new config option.

Would exactly do you mean with keywords?

**Comment by gsabater** [comment]
@macjuul I think that this maybe you don't need to complicate yourself so much.

Nobody is going to write `TODO:` at the middle of a sentence without wanting to place an anchor, and for you it is much easier to check for colons only that every type of comment symbols. 

The magic of anchors is that they work almost everywhere, .md, .env files, .html files, etc, also, now you can place an anchor in a tabbed comment. If you implement checking for anchors in the beggining of the line, would that functionality be gone?

And lastly, the more checks you do (upper and lowercase, colons, comment symbols, etc) would that consume more resources from the machine?

My suggestion is that you check only for colons (or something similar) and not worry about the rest.

**Comment by macjuul** [comment]
> @macjuul I think that this maybe you don't need to complicate yourself so much.
> 
> Nobody is going to write `TODO:` at the middle of a sentence without wanting to place an anchor, and for you it is much easier to check for colons only that every type of comment symbols.
> 
> The magic of anchors is that they work almost everywhere, .md, .env files, .html files, outside comments, in a tabbed comment, mark tags as anchors, etc. If you implement checking for anchors in the beggining of the line, would that functionality be gone?
> 
> And lastly, the more checks you do (upper and lowercase, colons, comment symbols, etc) would that consume more resources from the machine?
> 
> My suggestion is that you check only for colons (or something similar) and not worry about the rest.

Hmm, the only problem I see with requiring a colon (or hyphen for example) is that it may break many existing anchors for users, since all example images and gifs in the documentation depict the anchors without separation symbol. 

As for your questions, these checks will add very little overhead as I'm matching everything in one regex pattern, besides that, I can still check all file types for anchors, however I'd only check for specific symbols prefixing the anchors. Realistically, not a lot would change, only very few anchors outside of comments may need to be prefixed with a valid symbol.

**Comment by lonix1** [comment]
On the contrary, having "todo" in the middle of a sentence is a valid use case as the OP himself mentioned. Perhaps a better example is "section".

However I agree that to keep it simple, just match for the colon.

**Comment by macjuul** [comment]
The only issue I see with requiring colons is the fact it will break many existing anchors for everyone who doesnt currently use one (since colons were not directly supported at release, theres probably a lot of people). Another issue that arrises is that we'll lose the ability to place messageless anchors, for example

`<!-- TODO -->`

My plan right now is to see in which ways anchors can be placed, and which characters should be allowed infront of them (as mentioned earlier). This will ideally keep all legitimate anchors in tact, while filtering out tags it finds in regular text. Besides, this will mean commentless anchors will stay.

If this ends up being too much work, I'll implement a colon requirenment instead.

I'll keep this thread updated on my final decision. Making such a change while hundereds of people are using anchors in their own unique way means I have to be extremely careful changing such things. The last thing we want is people losing half their anchors due to an update.

Thanks for your time!

**Comment by Densorius** [comment]
Maybe you could make the separator optional? Then it's up to the user to set the separator.

These can include ":", "-" and/or a space (" "). These can be made default. The user will be able to edit the setting and take the " " out for example.

**Comment by gsabater** [comment]
Yeah, that would be a cool solution. Have a setting called separator. With
a space by default to not break retrocompatibility, and then let every user
use their own symbol.

**Comment by lonix1** [comment]
Yeah the obvious solution is to have a new config option, which i what I was originally recommending. We need to maintain backwards compatibility.

`"defaultSeparator": " "`

And if you ever decide to handle the case of the keyword/anchor/tag/whatever in the middle of a sentence, then add another config option:

`"ignoreKeywordWithinSentence": "false"`

**Comment by macjuul** [comment]
Sounds good guys, I'll try working on this today.
