### ISSUE TITLE
Epic anchors doesn't work

### ISSUE THREAD

**Issue by PlavcDav** [ExodiusStudios/vscode-comment-anchors#127]
File anchors works normally, but **epic doesn't work** in any type of project.

![cSharpProblem](https://user-images.githubusercontent.com/86932933/124400934-6cdf4780-dd26-11eb-8226-7811c54cbb6c.png)

![shellProblem](https://user-images.githubusercontent.com/86932933/124400923-576a1d80-dd26-11eb-9961-18208da1daf7.png)

**Comment by JordanDi123** [comment]
Hi there,

It looks like you are not in a workspace. You must be within a workspace for epic anchors to work.

Here is an example of your code working on my end. Please note that the NOTE anchor does not display because it does not have a scope of workspace:

![image](https://user-images.githubusercontent.com/24500399/125371786-8e0bed80-e34f-11eb-82cf-6b5755c2a77a.png)

If you happen to capture this within a workspace and the epics are still not displaying, please follow up with more information.

Thank you for using Comment Anchors! :)
