### ISSUE TITLE
Not working with hangul(korean language)

### ISSUE THREAD

**Issue by wangtae** [ExodiusStudios/vscode-comment-anchors#17]
When i use thie <tag> with hangul(korean language) highlight is disabled.

For example, 

// ANCHOR This is a anchor   -> highlight is enabled
// ANCHOR This is a anchor 이것은 앵커입니다.  -> highlight is enabled but just displayed english text in sidebar.
// ANCHOR 이것은 앵커입니다. -> highlight is disabled.

please check this one.

**Comment by macjuul** [comment]
Thank you for bringing this issue to light!

Since this seems like a technical limitation of RegEx, it was challenging to find a nice solution for this problem. I've fixed this by allowing comment anchor comments to be surrounded by double quotes, allowing you to specify what belongs to the anchor.

![image](https://user-images.githubusercontent.com/7606171/46544073-e1a99c80-c8c2-11e8-8810-d82f0bb2e2b5.png)

Even though this means you may have to add two more characters, this fix should support all non-English characters, including symbols and emojis. This functionality will be available in a few days time in version 1.6.1.

Hopefully this helps you!
