### ISSUE TITLE
Vscode craches when file scanning takes more then 10s

### ISSUE THREAD

**Issue by mjarkk** [ExodiusStudios/vscode-comment-anchors#18]
Sinds the latest vscode update (v1.28.0) a extension needs to response within 10s otherwise vscode will assume the extension is somewhat dead and will give a popup `extension host terminated unexpectedly` for some reason this disables all other extensions and stops a lot of other editor functions.  

For a more detailed issue look at this issue: https://github.com/Microsoft/vscode/issues/60465

**Comment by macjuul** [comment]
Hi,

I've been testing the loading of large directories with my team, however we can't seem to reproduce the issue as severe as you are getting it (Rarely we receive an "extension host is unresponsive" popup).

Since this seems to be caused by the loop that scans all workspace files, and can probably differ a lot between machines and operating systems, I'll implement a timeout to prevent the loop from completely blocking the process for longer than 10 seconds.

In case you still receive these problems in the next version, please report back to this issue. 

(PS It appears that 1.28.1, which just released, has removed the popup again)

Thanks!

**Comment by mjarkk** [comment]
Np, I'll update everything and see if this fixes the issue.
