### ISSUE TITLE
Detect anchors across the workspace

### ISSUE THREAD

**Issue by Densorius** [ExodiusStudios/vscode-comment-anchors#3]
Thanks for this great extension.
Could you add the functionality to detect all comment anchors across the workspace?

**Comment by macjuul** [comment]
Thanks for the suggestion! I'll look into the possibility of adding workspace anchors over the next few days.

Since the original goal of CA was to provide easy navigation in the current file, I'll keep this functionality as it currently is, and will most likely add a second pane to the sidebar for "workspace anchors".

**Comment by GammaGames** [comment]
It might be nice to have settings for the workspace tags. You could give a setting for `'commentAnchors.workspaceTags.list': []` so that users could have only the 'TODO' and 'FIXME' tags show up in the workspace list, since showing every note and anchor across all files could get cluttered.

As for showing the anchors, they could be in a 'Workspace' section inside the anchor panel (similar to how the [outline view](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) works).  It could even be a tree, so you could collapse files!

**Comment by macjuul** [comment]
It took me a whole lot of refactoring but I've successfully managed to implement workspace anchors. Before publishing it I'll be testing it a bit more to make sure it doesn't contain any critical bugs.

And again, thanks for your suggestion!

![image](https://user-images.githubusercontent.com/7606171/45922682-34eb1a80-bed3-11e8-8ca6-7fab3ffc51c2.png)

**Comment by GammaGames** [comment]
Awesome work :D Will add a written review soon

**Comment by gsabater** [comment]
Is there any way to exclude folders from the workspace scan?
For large projects scanning anchors takes almost a minute

**Comment by macjuul** [comment]
@gsabater You can change which files and folders are included and excluded using the 'Match files' and 'Exclude files' settings. By default all files are scanned, so I suggest limiting the scan to specific extensions.

Here is an example to match only .js and .ts files:

**Match files**: `**/*{.js,.ts}`

Sorry for the inconvenience!
