### ISSUE TITLE
[ Feature Request ] How can I set break point?

### ISSUE THREAD

**Issue by Akasan** [ExodiusStudios/vscode-comment-anchors#41]
Hi !
I'm sorry that my English is not good.

Now, I'm using comment anchors.
I can't set break point when I want to debug.
When I click the left of the number of line, there's no check of break point.
There's already anchor simbol , so I can't click and set break point.

Is it possible to set break point??

**Comment by Bitheral** [comment]
Hello, sorry that it's been a long time for a response.

It is possible to set a breakpoint with a Comment Anchor on the same line, you can simply do: Debug > Toggle Breakpoint, or use its shortcut (Default: F9). This will place a breakpoint on the line your keyboard cursor is currently on. (The line you have selected)

Now, as you stated, it does replace the breakpoint symbol with an anchor, however this is more related to  VS Code itself rather the Comment Anchors extension. It is currently suggested to include your breakpoint in your comment anchor, so that you'll know where you've placed breakpoints in your code. Something along the lines of ``//TODO Example comment [Breakpoint]`` should be suffice.

**Comment by Akasan** [comment]
Thank you for your response!

OK.
I'll try.
