### ISSUE TITLE
Disable Sidebar Auto-Folding

### ISSUE THREAD

**Issue by Volkward** [ExodiusStudios/vscode-comment-anchors#50]
I am using comment anchors with nested regions and it works quite fine. 
But every time I make changes to a file, the anchor sidebar automatically folds ALL Sub-Sections and only the Sections at the very top are shown which can be really stressful for bigger projects.
So for example my structure looks like this in the sidebar:

∨ Top-Section 1
   ∨ Sub-Section 1.1
         Sub-Section 1.2
∨ Top-Section 2
   ∨ Sub-Section 2.1
         Sub-Section 2.2

No I change a line in the respective file, and I automatically get this in the sidebar:

≻  Top-Section 1
≻ Top-Section 2

I didn't even hit 'Save'. It just folds all Sub-Sections and I have to manually re-open them.
Any chance, this behavior can be improved in future releases? A big improvement for example would be to have a 'fold/unfold all anchors' option in the comment anchors sidebar.

**Comment by MarcosPer** [comment]
Me too with laravel blades using @onecentlin extension laravel-blade-snippets-vscode. https://github.com/onecentlin/laravel-blade-snippets-vscode In my case i removed this extension because i only use it as complement meanwhile the full support for laravel blade is necessary in my everyday work.

Greetings, I hope that it will be resolved soon because i love this extension

**Comment by marvinhosea** [comment]
Disable the auto-folding. What i have done at the moment is disable it and enable it only when i need to use it

**Comment by macjuul** [comment]
I've tried my hand at implementing folding retention, however I could not figure out how to do so. Anyone is free to give it a shot and PR a fix, until then I'll close this issue.
