### ISSUE TITLE
Extremly slow & blocks everything.

### ISSUE THREAD

**Issue by kbumsik** [ExodiusStudios/vscode-comment-anchors#55]
Hi,
I came across this extension today and seemed promising. However, I noticed that VS Code gets very slow when I enable this in a pretty big workspace with 6 projects.
Specifically, while this extension is in parsing state, VIM extension is blocked so that I cannot even type anything. Also I noticed that renaming a file does not have any effect (I cannot change a filename of any file).

I guess this extension triggers too many events at once that any other extensions are blocked until it finishes parsing.

**Comment by macjuul** [comment]
The blocking is primarily caused by the scanning of workspace anchors. As of version 1.7.0 the workspace scanner no longer starts automatically by default. If using workspace anchors is still desired, the extension offers multiple settings to improve the efficiency of the workspace scan, which will hopefully eliminate most if not all issues.
