### ISSUE TITLE
[bug]Comment Anchors broken the vs code collapse/expand feature

### ISSUE THREAD

**Issue by betgar** [ExodiusStudios/vscode-comment-anchors#61]
I'am a vuejs developer, when i use Comment Anchors and vetur plugin , i found the vetur collapse /expand  code feature (in the *.vue file) was broken. I disabled the Comment Anchors plugin and reload the vs code, vetur collapse/ expand feature  is back.

**env:** 
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Comment Anchors v1.6.1
vetur v0.22.2  (https://github.com/vuejs/vetur)

![reproduce](https://user-images.githubusercontent.com/15810150/63738881-e2be3080-c8bd-11e9-98a0-b9e5f569d488.gif)

**Comment by betgar** [comment]
I made a mistake, the collapse/expend feature is belong vs code not the vetur plugin.

**Comment by bitsy** [comment]
**Comment Anchors:**
 v1.6.1 (according to the [changelog](https://marketplace.visualstudio.com/items/ExodiusStudios.comment-anchors/changelog), with latest commit e4ed641)

**VS Code:**
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Operating System:**
MacOS Mojave Version 10.14.6 (18G87)

**The Problem and a Quick Fix:**
I'm also experiencing this issue, and can reproduce the problem with any .cpp, .h, or .py file. With Comment Anchors enabled, the code folding feature in VS Code stops working. I've found that the easiest solution to this problem (without disabling the extension) is to disable "Comment Anchors: Editor Folding" in User Settings:
<img width="787" alt="Screen Shot 2019-09-09 at 18 03 06" src="https://user-images.githubusercontent.com/36607587/64576215-76ffad00-d32c-11e9-9af5-74a3ec570a9d.png">
It seems that the issue is somewhat known, considering the disclaimer "This feature is known to conflict with some language extensions." However, I am disappointed that it conflicts with such popular languages like C++ and Python. In my honest opinion, the feature shouldn't even be included in the stable release until it can handle these languages.

**Comment by betgar** [comment]
Thank you for your answer. This thing bothers me for a long time.
