### ISSUE TITLE
CPU and RAM usage through the roof

### ISSUE THREAD

**Issue by tonykaram1993** [ExodiusStudios/vscode-comment-anchors#8]
I just uninstalled this extension because it was causing a lot of issues. Today (this did not happen before today, and I had the extension installed for at least a full month), out if nowhere vscode was using 80-90% CPU usage and 4-5 GB of RAM. 

After some plugin disabling and troubleshooting, it turns out that its Comment Anchors that was causing this. If the plugin was disabled, vscode behaves normally, if it was enabled, BAM cpu and ram are through the roof.

Relevant specs: 16 GB Ram - i7 6700K 4.6GHz (4 cores - 8 threads)

**Comment by macjuul** [comment]
As @gsabater said, this is indeed an issue caused by the new workspace anchors feature, and the broad scanning filter. The approach we are taking to search the anchors appears to be extremely slow, causing the performance issues.

We're currently working on an alternative method that should clear up most, if not all, performance issues.

I'm honestly extremely sorry this update caused all these issues, and will try to release an update as soon as possible.

**Comment by tonykaram1993** [comment]
Alright, thank you for the heads up.

**Comment by macjuul** [comment]
Hey there,

I've reworked the scanner to behave much faster, alongside improving the default excluding pattern. Besides that, you can now disable workspace scanning all together if you decide you'd rather not use it.

Since Comment Anchors are meant to be used in any kind of file, I've kept the default match pattern to all file types. This setting can of course still be adjusted to suit your personal workflow for even more performance gains.

The fix should be live now, thanks for your patience.

**Comment by GammaGames** [comment]
Just got it, it's running significantly faster! Thank you for your work :)

**Comment by gsabater** [comment]
@macjuul Nice work, it works better now.

I have two suggestions tho, nothing important.

- I'd add `vendor` to the default excluding list. A lot of people who work at php projects use composer and have a LARGE vendor folder. 
- How hard would it be to add a third option to the scan workspace toggle? It would be cool if we could have the sync disabled, but when we open the anchors page in the action menu, then, starts the workspace scan. Those are a few precious seconds on startup that can be avoided, for people who open projects all the time to check for code.

THANKS for your amazing and fast work

**Comment by macjuul** [comment]
@gsabater Thanks! Good to know!

I've just added vendor to the list of excluded folders, and as for the delayed workspace scanning, this is the closest I can get it

![lazy-workspace](https://user-images.githubusercontent.com/7606171/46132432-44a19080-c23e-11e8-862a-f70b365141bc.gif)

I'm still aiming to implement anchor regions before releasing the next update, though

**Comment by gsabater** [comment]
@macjuul That screen is in fact exactly was i was asking for.
Don't rush your updates and keep it up with the good work.
